updated retry logic and added test
wealthsimple/llm-gateway pull request #19
Opened 2023-08-18 18:51 UTC by edwardcqian

**Why is this change being made?**
The previous change to the retry logic is catching exceptions incorrectly.

Python can't catch a list of exception

**What is changing?**
Catch the exception and checking if it is in the list of exceptions to exempt.

**How did I test?**
- Added a test case
- run the service and test with the following
```
curl -X 'POST' \
  'http://localhost:5000/api/openai/completion' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "temperature": 0,
  "prompt": "bark like a dog",
  "max_tokens": 50,
  "model": "this-model-does-not-exist",
  "model_kwargs": {}
}'
```

2023-08-18 19:25 UTC, metavee commented on llm_gateway/utils.py
> +                except Exception as e:
If you want to try it the original way, I think it would actually work if you made `exceptions` into a tuple instead of a list!

E.g., this works in the REPL:

```
exceptions = (ValueError, TypeError)

try:
    float("abc")
except exceptions as e:
    print("exception caught")
```

2023-08-20 03:30 UTC, edwardcqian commented on llm_gateway/utils.py
> +                except Exception as e:
Ah okay, tuple makes more sense. Updated.

2023-08-20 03:31 UTC, edwardcqian commented
Also updated the test, previous test wasn't actually testing the matching error retry local properly.

2023-08-21 13:49 UTC, metavee requested changes
Looking great, but two small things (with suggested edits):

- in Python, the expression `(abcdef)` is not a tuple of 1, it's just the item itself. So to show that the code works, we need to change these to `(abcdef,)`
- `retry_mock.side_effect` doesn't get reset between the different function calls, so it needs to be longer for the test to work as expected

2023-08-21 13:49 UTC, metavee commented on llm_gateway/utils.py
> +def max_retries(times: int, exceptions: tuple = (Exception)):
```suggestion
def max_retries(times: int, exceptions: tuple = (Exception,)):
```

2023-08-21 13:49 UTC, metavee commented on tests/test_utils.py
> +    @max_retries(1, exceptions=(ValueError))
```suggestion
    @max_retries(1, exceptions=(ValueError,))
```

2023-08-21 13:49 UTC, metavee commented on tests/test_utils.py
> +    @max_retries(1, exceptions=(APIError))
```suggestion
    @max_retries(1, exceptions=(APIError,))
```

2023-08-21 13:49 UTC, metavee commented on tests/test_utils.py
> +    retry_mock.side_effect = [APIError("test"), "success"]
```suggestion
    retry_mock.side_effect = [APIError("test"), APIError("test"), "success"]
```

Originally, the second time you called it (with `matching_exception`) it would just return `"success"` the first time, so the retry logic wasn't actually being tested.

2023-08-22 19:58 UTC, edwardcqian commented
> Looking great, but two small things (with suggested edits):
> 
> * in Python, the expression `(abcdef)` is not a tuple of 1, it's just the item itself. So to show that the code works, we need to change these to `(abcdef,)`
> * `retry_mock.side_effect` doesn't get reset between the different function calls, so it needs to be longer for the test to work as expected

Ah, great catches, thanks!

Ended up splitting the test case into two for clarity.

2023-08-22 22:42 UTC, metavee approved these changes

2023-08-22 22:43 UTC, merged

2023-08-22 22:43 UTC, metavee commented
Thanks!